FROM node:22.14.0

WORKDIR /usr/src/next

RUN apt-get update -qq && apt-get install -y nodejs npm && rm -rf /var/lib/apt/lists/*

COPY package*.json ./

RUN yarn install

COPY . .

RUN yarn build

CMD ["yarn", "start"]
